services:
  identity-db: #container içindeki sleepbench_identity veritabanı
    image: postgres:17-alpine #docker image: postgreSQL kurulumunun hazır şablonu
    container_name: sleepbench-identity-db #bu şablondan çalışan hazır postgreSQL processi
    environment:
      POSTGRES_DB: sleepbench_identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${IDENTITY_DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes: #verilerin container silinse bile kalmasını sağlayan alan
      - identity-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sleepbench_identity"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
    identity-db-data: